### ISSUE TITLE
调用createTextImage()报错

### ISSUE THREAD

**Issue by MediocreRex** [Sunny-117/text-image#1]
这是一个最小复现（大概）。报错内容为Uncaught (in promise): require "canvas" option，可能问的很浅显，但是弄了一个下午没懂，求大神解惑ORZ

test.vue
```javascript
<template>
    <div class="titleBox">
        123
    </div>
  
  </template>
  
  <script>
  import { createTextImage } from './text-image.js'
  export default {
  mounted() {
    createTextImage({
      canvas: document.querySelector('canvas'),
      source: {
        text: 'Text Image',
      },
    });
  }
};
  </script>
  
  <style scoped>
  .titleBox {
    background-color: blueviolet;
  }
  </style>
```

**Comment by Sunny-117** [comment]
你的模板里面没有<canvas></canvas>标签

**Comment by Sunny-117** [comment]
https://github.com/Sunny-117/text-image/commit/8acf42599722d2eb57aacf8a80c5b160118f3d33#diff-4f7403e31e6f4c3eb30e5b054db39bfd93075dcc14199440317e5fa3bb889ce9

**Comment by MediocreRex** [comment]
十分感谢您的指点和代码实例~我加入canvas标签后顺利完成了「文本化」。
不过在用同样的办法处理图片、视频时我遇到了新的问题，即Uncaught (in promise)，执行GPT给出的建议后也未能解决，我想请问您有没有解决的方向：
代码：
```javascript
<template>
  <canvas id="can1"></canvas>
  <canvas id="can2"></canvas>
</template>
<script setup>
import { createTextImage } from '../utils/text-image';
import { onMounted } from "vue";
onMounted(() => {
  createTextImage({
    canvas: document.querySelector("#can1"),
    source: {
      video: "./1.mp4",
    },
  });
  createTextImage({
    canvas: document.querySelector("#can2"),
    source: {
      text: "文本可以正常显示",
    },
  });
});
</script>
```

下面是在浏览器控制台显示的报错信息
```javascript
index.ts:104  Uncaught (in promise) Event {isTrusted: true, type: 'error', target: null, currentTarget: null, eventPhase: 0, …}
createTextImage @ index.ts:104
await in createTextImage(异步)
(匿名) @ test.vue:11
(匿名) @ runtime-core.esm-bundler.js:2875
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2855
flushPostFlushCbs @ runtime-core.esm-bundler.js:378
flushJobs @ runtime-core.esm-bundler.js:416
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:319
queuePostFlushCb @ runtime-core.esm-bundler.js:339
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1762
scheduler @ runtime-core.esm-bundler.js:1973
resetScheduling @ reactivity.esm-bundler.js:264
triggerEffects @ reactivity.esm-bundler.js:308
triggerRefValue @ reactivity.esm-bundler.js:1070
set value @ reactivity.esm-bundler.js:1115
finalizeNavigation @ vue-router.mjs:3361
(匿名) @ vue-router.mjs:3226
Promise.then(异步)
pushWithRedirect @ vue-router.mjs:3193
push @ vue-router.mjs:3118
install @ vue-router.mjs:3559
use @ runtime-core.esm-bundler.js:3856
(匿名) @ main.js:12
显示 20 更多框架
显示简略信息
```

**Comment by Sunny-117** [comment]
vite项目的话 把资源放在public目录下 https://cn.vitejs.dev/guide/assets#the-public-directory
然后这样配置：<template>
  <canvas id="can1"></canvas>
  <canvas id="can2"></canvas>
</template>
<script setup>
import { onMounted } from "vue";
import { createTextImage } from "@sunny-117/text-image";
onMounted(() => {
  createTextImage({
    canvas: document.querySelector("#can1"),
    replaceText: "6",
    source: {
      video: "../public/1.mp4",
    },
  });
});
</script>

![image](https://github.com/Sunny-117/text-image/assets/73089592/e2cfed5c-361d-419d-b69c-e617fe1284f3)
可以看我最新提交的commit

**Comment by MediocreRex** [comment]
十分感谢您，Sunny Fu老师



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sunny ***@***.***&gt;; 
发送时间: 2024年4月26日(星期五) 晚上6:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sunny-117/text-image] 调用createTextImage()报错 (Issue #1)














 
vite项目的话 把资源放在public目录下 https://cn.vitejs.dev/guide/assets#the-public-directory
 然后这样配置：
 <template&gt;   <canvas id="can1"&gt;</canvas&gt;   <canvas id="can2"&gt;</canvas&gt; </template&gt; <script setup&gt; import { onMounted } from "vue"; import { createTextImage } from ***@***.***/text-image"; onMounted(() =&gt; {   createTextImage({     canvas: document.querySelector("#can1"),     replaceText: "6",     source: {       video: "../public/1.mp4",     },   }); }); </script&gt;
 
image.png (view on web)
 可以看我最新提交的commit
